[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/auth/patreon"
  to = "/.netlify/functions/auth-patreon"
  status = 302
  force = true

[[redirects]]
  from = "/auth/patreon/callback"
  to = "/.netlify/functions/auth-patreon-callback"
  status = 302
  force = true

[[redirects]]
  from = "/auth/admin"
  to = "/.netlify/functions/admin-auth"
  status = 302
  force = true

[[redirects]]
  from = "/auth/admin/callback"
  to = "/.netlify/functions/admin-auth"
  status = 302
  force = true

[[redirects]]
  from = "/admin/export"
  to = "/.netlify/functions/admin-export"
  status = 302
  force = true

[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200
