name                   = "ttao-academy"
pages_build_output_dir = "."
compatibility_date     = "2025-01-01"

[[kv_namespaces]]
binding = "ARTICLES_KV"
id      = "57042f14d2c349adb4de84ff6f508f6c"

[[kv_namespaces]]
binding = "STUDENTS_KV"
id      = "0e1b069217264bfdb511c275bdbaaf41"
